# Generated by Django 4.1.4 on 2022-12-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuya_device_id', models.CharField(max_length=64, verbose_name='Tuya Device ID')),
                ('contents', models.CharField(max_length=256, verbose_name='Description of contents')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Time')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('prior_quiet', models.DurationField(verbose_name='Duration')),
                ('doors', models.JSONField()),
                ('overlaps', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Time')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openings', to='Doors.door')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openings', to='Doors.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('timestamp', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Tuya TimeStamp')),
                ('source', models.CharField(max_length=64, verbose_name='Tuya event source')),
                ('code', models.CharField(max_length=64, verbose_name='Tuya event code')),
                ('type', models.CharField(max_length=64, verbose_name='Tuya event type')),
                ('value', models.CharField(max_length=64, verbose_name='Tuya event value')),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='Doors.door')),
            ],
        ),
    ]
