# Generated by Django 4.1.4 on 2022-12-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doors', '0002_Montagu_Street_Library_Doors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openings', to='Doors.visit'),
        ),
        migrations.CreateModel(
            name='Uptime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Time')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('offline_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='went_down', to='Doors.event')),
                ('online_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='went_up', to='Doors.event')),
            ],
        ),
    ]
