# Generated by Django 4.1.4 on 2023-02-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doors', '0004_uptime_door'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFetch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Time')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='data_fetch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='Doors.datafetch'),
        ),
    ]
